### ISSUE TITLE
MocoAverageSpeedGoal unrecognized when reading MocoStudy from xml

### ISSUE THREAD

**Issue by SolaWeng** [opensim-org/opensim-moco#662]
The MocoAverageSpeedGoal seems to be unrecognized when reading a saved MocoStudy xml file.

I am using MATLAB 2020b with OpenSim Moco 0.4.0 on windows 10. I used the example2DWalking with additional lines at the end:

`study.print("study.xml");`
`MocoStudy("study.xml");`

Error message:
`Encountered unrecognized Object typename MocoAverageSpeedGoal while reading property goals. There is no registered Object of this type; ignoring.`

Feels like this is a bug. Just to want to bring this to your attention.

**Comment by antoinefalisse** [comment]
Thanks @SolaWeng for reporting this issue.
Moco has now been merged in OpenSim, and this bug has been corrected, see [here](https://github.com/opensim-org/opensim-core/pull/2917).
If this bug is blocking you for making further progress, you can remove the `MocoAverageSpeedGoal ` from the .xml file, create your study `MocoStudy("study.xml");`, and add the goal back programmatically.

**Comment by SolaWeng** [comment]
Hi Antoine, 

Thanks for the update! For now I can just redefine the MocoAverageSpeedGoal in MATLAB. It's not a big issue.

Cheers,
Sola
